version: '3'
services:
  web:
    build: ./coffee-app
    ports:
    - "80:80"
    links:
    - node
    volumes:
    - /home/kg/Code/coffee/coffee-app/dist:/usr/share/nginx/html
  node:
    build: ./coffee-node-app
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"